%% consolidate_spacex_matlab_legacy_data_epoch_complete
%
% Consolidate and export the valuable legacy MATLAB/GISMO products from the
% 2016 Falcon 9 explosion analysis.
%
% This script:
%   1. inventories all MAT files in INPUT_DIR;
%   2. loads spacexplosion.mat;
%   3. extracts all manual Antelope/GISMO arrival picks;
%   4. parses station, location, and channel codes from channelinfo;
%   5. preserves original phase labels and adds convenience flags;
%   6. associates picks with the 153-event infrasoundEvent catalogue;
%   7. validates the reconstructed 153-event pick associations;
%   8. creates a broad accident-window pick subset;
%   9. exports a flat 153-event legacy catalogue;
%  10. optionally exports the 157-event catalog.mat catalogue;
%  11. writes durable CSV/MAT products and summary reports.
%
% Time handling
% -------------
% All important times are exported in three forms:
%
%   - original MATLAB datenum;
%   - Unix epoch seconds as double precision;
%   - UTC datetime formatted to milliseconds.
%
% The epoch-second columns should be treated as the preferred interchange
% representation in Python.
%
% The manual arrival times are the primary archival product. Original picks
% and phase labels are never discarded.
%
% Requirements:
%   - MATLAB
%   - GISMO on the MATLAB path, so Arrival/Catalog objects can be loaded
%   - spacexplosion.mat in INPUT_DIR
%
% Main outputs:
%   legacy_export/
%       mat_file_inventory.csv
%       mat_file_inventory.mat
%       mat_file_inventory.txt
%       manual_arrival_picks.csv
%       accident_arrival_picks.csv
%       explosion_event_arrival_picks.csv
%       unassociated_arrival_picks.csv
%       legacy_infrasound_event_catalogue.csv
%       event_pick_association_validation.csv
%       legacy_catalog_157_events.csv          (when catalog.mat is present)
%       legacy_spacex_archive.mat
%       legacy_export_summary.txt
%
% Glenn Thompson / consolidated workflow

clearvars;
clc;

%% ------------------------------------------------------------------------
% Configuration
% -------------------------------------------------------------------------

INPUT_DIR = ...
    '/Users/thompsong/Library/CloudStorage/Box-Box/thompsong/' + ...
    "3_Project_Documents/NASAprojects/201602_Rocket_Seismology/" + ...
    "02_KSC/matlab/data";

INPUT_DIR = char(INPUT_DIR);

INPUT_MAT_FILE = fullfile(INPUT_DIR, 'spacexplosion.mat');
CATALOG_MAT_FILE = fullfile(INPUT_DIR, 'catalog.mat');

METADATA_DIR = ...
    '/Users/thompsong/Developer/KSCRocketSeismology/' + ...
    "08_fireball_paper/metadata";

METADATA_DIR = char(METADATA_DIR);
OUTPUT_DIR = fullfile(METADATA_DIR, 'legacy_export');

UNIX_EPOCH_DATENUM = datenum(1970, 1, 1);

% Broad interval used for a convenient pick subset. This currently includes
% the full review interval on 1–2 September.
ACCIDENT_START_UTC = datetime( ...
    2016, 9, 1, 0, 0, 0, ...
    'TimeZone', 'UTC' ...
);

ACCIDENT_END_UTC = datetime( ...
    2016, 9, 2, 23, 59, 59, ...
    'TimeZone', 'UTC' ...
);

% Exact event-boundary matching tolerance for accepted infrasound N picks.
BOUNDARY_TOLERANCE_S = 0.002;

% Wider tolerance used only when associating auxiliary seismic/deleted picks
% with the nearest already-defined event.
AUXILIARY_PICK_TOLERANCE_S = 0.15;

% Tie tolerance when two events are equally close to an auxiliary pick.
TIE_TOLERANCE_S = 1.0e-6;

% Maximum mismatch allowed in the validation report.
EVENT_BOUNDARY_VALIDATION_TOLERANCE_MS = 5.0;

% Millisecond-level display format written to CSV.
DATETIME_FORMAT = 'yyyy-MM-dd''T''HH:mm:ss.SSS';

if ~isfolder(OUTPUT_DIR)
    mkdir(OUTPUT_DIR);
end

if ~isfile(INPUT_MAT_FILE)
    error('Input file not found: %s', INPUT_MAT_FILE);
end

fprintf('Input directory:\n  %s\n', INPUT_DIR);
fprintf('Output directory:\n  %s\n\n', OUTPUT_DIR);

%% ------------------------------------------------------------------------
% 1. Inventory all MAT files
% -------------------------------------------------------------------------

fprintf('1. Inventorying MAT files...\n');

matFiles = dir(fullfile(INPUT_DIR, '*.mat'));

inventoryRows = struct( ...
    'file', {}, ...
    'variable', {}, ...
    'class', {}, ...
    'size_text', {}, ...
    'numel', {}, ...
    'bytes', {}, ...
    'is_complex', {}, ...
    'is_global', {}, ...
    'is_sparse', {} ...
);

for fileIndex = 1:numel(matFiles)

    filename = fullfile(matFiles(fileIndex).folder, matFiles(fileIndex).name);

    try
        info = whos('-file', filename);
    catch ME
        warning('Could not inspect %s: %s', filename, ME.message);
        continue
    end

    for variableIndex = 1:numel(info)

        item = info(variableIndex);
        sizeText = strjoin(string(item.size), ' x ');

        inventoryRows(end + 1) = struct( ... %#ok<SAGROW>
            'file', matFiles(fileIndex).name, ...
            'variable', item.name, ...
            'class', item.class, ...
            'size_text', char(sizeText), ...
            'numel', prod(double(item.size)), ...
            'bytes', double(item.bytes), ...
            'is_complex', logical(item.complex), ...
            'is_global', logical(item.global), ...
            'is_sparse', logical(item.sparse) ...
        );
    end
end

if isempty(inventoryRows)
    inventoryTable = table();
else
    inventoryTable = struct2table(inventoryRows);
    inventoryTable = sortrows( ...
        inventoryTable, ...
        {'file', 'bytes'}, ...
        {'ascend', 'descend'} ...
    );
end

writetable( ...
    inventoryTable, ...
    fullfile(OUTPUT_DIR, 'mat_file_inventory.csv') ...
);

save( ...
    fullfile(OUTPUT_DIR, 'mat_file_inventory.mat'), ...
    'inventoryTable' ...
);

inventoryTextFile = fullfile(OUTPUT_DIR, 'mat_file_inventory.txt');
fidInventory = fopen(inventoryTextFile, 'w');

if fidInventory < 0
    error('Could not create %s', inventoryTextFile);
end

cleanupInventory = onCleanup(@() fclose(fidInventory));

if ~isempty(inventoryTable)

    uniqueFiles = unique(inventoryTable.file, 'stable');

    for fileIndex = 1:numel(uniqueFiles)

        thisFile = uniqueFiles{fileIndex};
        rows = inventoryTable(strcmp(inventoryTable.file, thisFile), :);

        fprintf(fidInventory, '%s\n', repmat('=', 1, 72));
        fprintf(fidInventory, '%s\n', thisFile);
        fprintf(fidInventory, '%s\n', repmat('=', 1, 72));

        for rowIndex = 1:height(rows)
            fprintf( ...
                fidInventory, ...
                '%-40s %-18s %-18s %12.3f MB\n', ...
                rows.variable{rowIndex}, ...
                rows.class{rowIndex}, ...
                rows.size_text{rowIndex}, ...
                rows.bytes(rowIndex) / 1024^2 ...
            );
        end

        fprintf(fidInventory, '\n');
    end
end

clear cleanupInventory;
fprintf('   Found %d MAT files.\n', numel(matFiles));

%% ------------------------------------------------------------------------
% 2. Load the legacy workspace
% -------------------------------------------------------------------------

fprintf('2. Loading %s...\n', INPUT_MAT_FILE);

legacy = load(INPUT_MAT_FILE);

requiredVariables = {'arrivals', 'infrasoundEvent', 'wevent'};

for k = 1:numel(requiredVariables)
    if ~isfield(legacy, requiredVariables{k})
        error( ...
            'Required variable %s is missing from %s', ...
            requiredVariables{k}, ...
            INPUT_MAT_FILE ...
        );
    end
end

arrivals = legacy.arrivals;
infrasoundEvent = legacy.infrasoundEvent;
wevent = legacy.wevent;

fprintf('   Arrival picks: %d\n', numel(arrivals.time));
fprintf('   Infrasound events: %d\n', numel(infrasoundEvent));
fprintf('   Event waveform cells: %d\n', numel(wevent));

%% ------------------------------------------------------------------------
% 3. Extract and parse all manual arrival picks
% -------------------------------------------------------------------------

fprintf('3. Extracting and parsing manual arrival picks...\n');

nPicks = numel(arrivals.time);

pickIndex = (1:nPicks)';
arid = nan(nPicks, 1);

matlabDatenum = nan(nPicks, 1);
arrivalTimeEpochS = nan(nPicks, 1);
arrivalTimeUTC = NaT(nPicks, 1, 'TimeZone', 'UTC');

network = strings(nPicks, 1);
station = strings(nPicks, 1);
location = strings(nPicks, 1);
channel = strings(nPicks, 1);
seedId = strings(nPicks, 1);
channelInfoText = strings(nPicks, 1);
channelParseSucceeded = false(nPicks, 1);

phase = strings(nPicks, 1);
amplitude = nan(nPicks, 1);
signalToNoise = nan(nPicks, 1);
timeUncertaintyS = nan(nPicks, 1);

channelExpression = ...
    '^\.(?<station>[^.]+)\.\.(?<channel>[A-Za-z0-9]{3})_(?<location>[A-Za-z0-9]{2})$';

for pickNumber = 1:nPicks

    pickDatenum = arrivals.time(pickNumber);

    matlabDatenum(pickNumber) = pickDatenum;
    arrivalTimeEpochS(pickNumber) = ...
        (pickDatenum - UNIX_EPOCH_DATENUM) * 86400;

    arrivalTimeUTC(pickNumber) = datetime( ...
        pickDatenum, ...
        'ConvertFrom', 'datenum', ...
        'TimeZone', 'UTC' ...
    );

    if ~isempty(arrivals.arid)
        arid(pickNumber) = arrivals.arid(pickNumber);
    end

    if ~isempty(arrivals.iphase)
        phase(pickNumber) = string(arrivals.iphase{pickNumber});
    end

    if ~isempty(arrivals.amp)
        amplitude(pickNumber) = arrivals.amp(pickNumber);
    end

    if ~isempty(arrivals.signal2noise)
        signalToNoise(pickNumber) = arrivals.signal2noise(pickNumber);
    end

    if ~isempty(arrivals.deltim)
        timeUncertaintyS(pickNumber) = arrivals.deltim(pickNumber);
    end

    info = arrivals.channelinfo{pickNumber};

    raw = string(evalc('disp(info)'));
    raw = strip(erase(raw, [newline, char(13)]));

    channelInfoText(pickNumber) = raw;

    match = regexp(raw, channelExpression, 'names', 'once');

    if ~isempty(match)

        station(pickNumber) = string(match.station);
        channel(pickNumber) = upper(string(match.channel));
        location(pickNumber) = string(match.location);

        % The legacy GISMO string contains no network code.
        network(pickNumber) = "";

        seedId(pickNumber) = strjoin( ...
            [ ...
                network(pickNumber), ...
                station(pickNumber), ...
                location(pickNumber), ...
                channel(pickNumber) ...
            ], ...
            "." ...
        );

        channelParseSucceeded(pickNumber) = true;
    end
end

arrivalTimeUTC.Format = DATETIME_FORMAT;

phaseNormalized = lower(strip(phase));

isDeleted = phaseNormalized == "del";
isInfrasoundPhase = phaseNormalized == "n";
isSeismicPhase = ismember(phaseNormalized, ["p", "s"]);
isUnclassifiedPhase = strlength(phaseNormalized) == 0;
isInfrasoundChannel = ismember(channel, ["HD1", "HD2", "HD3"]);
isSeismicChannel = ismember(channel, ["HHE", "HHN", "HHZ"]);

manualArrivalPicks = table( ...
    pickIndex, ...
    arid, ...
    matlabDatenum, ...
    arrivalTimeEpochS, ...
    arrivalTimeUTC, ...
    network, ...
    station, ...
    location, ...
    channel, ...
    seedId, ...
    phase, ...
    amplitude, ...
    signalToNoise, ...
    timeUncertaintyS, ...
    channelInfoText, ...
    channelParseSucceeded, ...
    isDeleted, ...
    isInfrasoundPhase, ...
    isSeismicPhase, ...
    isUnclassifiedPhase, ...
    isInfrasoundChannel, ...
    isSeismicChannel ...
);

manualArrivalPicks = sortrows( ...
    manualArrivalPicks, ...
    {'matlabDatenum', 'seedId'} ...
);

nParsed = sum(manualArrivalPicks.channelParseSucceeded);
fprintf('   Parsed %d of %d channel identifiers.\n', nParsed, nPicks);

if nParsed ~= nPicks
    warning('%d channel identifiers could not be parsed.', nPicks - nParsed);
end

%% ------------------------------------------------------------------------
% 4. Associate accepted infrasound N picks with the 153-event catalogue
% -------------------------------------------------------------------------

fprintf('4. Associating accepted infrasound N picks with legacy events...\n');

nEvents = numel(infrasoundEvent);
nPicks = height(manualArrivalPicks);

pickTimes = manualArrivalPicks.matlabDatenum;
phaseNormalized = lower(strip(manualArrivalPicks.phase));

isAcceptedInfrasoundNPick = ...
    phaseNormalized == "n" ...
    & manualArrivalPicks.isInfrasoundChannel;

boundaryToleranceDays = BOUNDARY_TOLERANCE_S / 86400;

eventNumberForPick = nan(nPicks, 1);
associationMethod = strings(nPicks, 1);
associationTimeResidualS = nan(nPicks, 1);
associationAmbiguous = false(nPicks, 1);

eventFirstArrivalDatenumForPick = nan(nPicks, 1);
eventLastArrivalDatenumForPick = nan(nPicks, 1);

eventFirstArrivalEpochSForPick = nan(nPicks, 1);
eventLastArrivalEpochSForPick = nan(nPicks, 1);

eventFirstArrivalUTCForPick = NaT(nPicks, 1, 'TimeZone', 'UTC');
eventLastArrivalUTCForPick = NaT(nPicks, 1, 'TimeZone', 'UTC');

timeFromEventFirstArrivalS = nan(nPicks, 1);

eventStarts = arrayfun( ...
    @(event) event.FirstArrivalTime, ...
    infrasoundEvent ...
);

eventEnds = arrayfun( ...
    @(event) event.LastArrivalTime, ...
    infrasoundEvent ...
);

for eventIndex = 1:nEvents

    t0 = eventStarts(eventIndex);
    t1 = eventEnds(eventIndex);

    inStoredBounds = ...
        isAcceptedInfrasoundNPick ...
        & pickTimes >= (t0 - boundaryToleranceDays) ...
        & pickTimes <= (t1 + boundaryToleranceDays);

    indices = find(inStoredBounds);

    if isempty(indices)
        warning( ...
            'Event %d has no accepted infrasound N picks in its stored bounds.', ...
            eventIndex ...
        );
        continue
    end

    alreadyAssigned = ~isnan(eventNumberForPick(indices));

    if any(alreadyAssigned)
        associationAmbiguous(indices(alreadyAssigned)) = true;

        warning( ...
            ['Event %d overlaps %d accepted infrasound N picks already ' ...
             'assigned to another event. Conflicting picks retain their ' ...
             'first assignment.'], ...
            eventIndex, ...
            sum(alreadyAssigned) ...
        );

        indices = indices(~alreadyAssigned);
    end

    eventNumberForPick(indices) = eventIndex;
    associationMethod(indices) = "stored_event_bounds";
    associationTimeResidualS(indices) = 0.0;

    eventFirstArrivalDatenumForPick(indices) = t0;
    eventLastArrivalDatenumForPick(indices) = t1;

    eventFirstArrivalEpochSForPick(indices) = ...
        (t0 - UNIX_EPOCH_DATENUM) * 86400;

    eventLastArrivalEpochSForPick(indices) = ...
        (t1 - UNIX_EPOCH_DATENUM) * 86400;

    eventFirstArrivalUTCForPick(indices) = datetime( ...
        t0, ...
        'ConvertFrom', 'datenum', ...
        'TimeZone', 'UTC' ...
    );

    eventLastArrivalUTCForPick(indices) = datetime( ...
        t1, ...
        'ConvertFrom', 'datenum', ...
        'TimeZone', 'UTC' ...
    );

    timeFromEventFirstArrivalS(indices) = ...
        (pickTimes(indices) - t0) * 86400;
end

nAcceptedNAssigned = sum( ...
    ~isnan(eventNumberForPick) ...
    & isAcceptedInfrasoundNPick ...
);

fprintf( ...
    '   Assigned accepted infrasound N picks: %d of %d\n', ...
    nAcceptedNAssigned, ...
    sum(isAcceptedInfrasoundNPick) ...
);

%% ------------------------------------------------------------------------
% 5. Associate remaining nearby picks with the nearest 153-event window
% -------------------------------------------------------------------------

fprintf('5. Associating remaining nearby picks with the nearest event...\n');

unassignedIndices = find(isnan(eventNumberForPick));

for pickRow = unassignedIndices'

    pickTime = pickTimes(pickRow);

    % Distance from the pick to each closed event interval. Zero means that
    % the pick lies inside the stored event interval.
    intervalDistanceS = zeros(1, nEvents);

    beforeEvent = pickTime < eventStarts;
    afterEvent = pickTime > eventEnds;

    intervalDistanceS(beforeEvent) = ...
        (eventStarts(beforeEvent) - pickTime) * 86400;

    intervalDistanceS(afterEvent) = ...
        (pickTime - eventEnds(afterEvent)) * 86400;

    [minimumDistanceS, nearestEvent] = min(intervalDistanceS);

    if minimumDistanceS > AUXILIARY_PICK_TOLERANCE_S
        continue
    end

    tiedEvents = find( ...
        abs(intervalDistanceS - minimumDistanceS) <= TIE_TOLERANCE_S ...
    );

    if numel(tiedEvents) > 1
        associationAmbiguous(pickRow) = true;
        associationMethod(pickRow) = "ambiguous_nearest_event";
        associationTimeResidualS(pickRow) = minimumDistanceS;
        continue
    end

    eventNumberForPick(pickRow) = nearestEvent;
    associationMethod(pickRow) = "nearest_event";
    associationTimeResidualS(pickRow) = minimumDistanceS;

    t0 = eventStarts(nearestEvent);
    t1 = eventEnds(nearestEvent);

    eventFirstArrivalDatenumForPick(pickRow) = t0;
    eventLastArrivalDatenumForPick(pickRow) = t1;

    eventFirstArrivalEpochSForPick(pickRow) = ...
        (t0 - UNIX_EPOCH_DATENUM) * 86400;

    eventLastArrivalEpochSForPick(pickRow) = ...
        (t1 - UNIX_EPOCH_DATENUM) * 86400;

    eventFirstArrivalUTCForPick(pickRow) = datetime( ...
        t0, ...
        'ConvertFrom', 'datenum', ...
        'TimeZone', 'UTC' ...
    );

    eventLastArrivalUTCForPick(pickRow) = datetime( ...
        t1, ...
        'ConvertFrom', 'datenum', ...
        'TimeZone', 'UTC' ...
    );

    timeFromEventFirstArrivalS(pickRow) = ...
        (pickTime - t0) * 86400;
end

eventFirstArrivalUTCForPick.Format = DATETIME_FORMAT;
eventLastArrivalUTCForPick.Format = DATETIME_FORMAT;

manualArrivalPicks.eventNumber = eventNumberForPick;
manualArrivalPicks.associationMethod = associationMethod;
manualArrivalPicks.associationTimeResidualS = associationTimeResidualS;
manualArrivalPicks.associationAmbiguous = associationAmbiguous;

manualArrivalPicks.eventFirstArrivalDatenum = ...
    eventFirstArrivalDatenumForPick;
manualArrivalPicks.eventLastArrivalDatenum = ...
    eventLastArrivalDatenumForPick;

manualArrivalPicks.eventFirstArrivalEpochS = ...
    eventFirstArrivalEpochSForPick;
manualArrivalPicks.eventLastArrivalEpochS = ...
    eventLastArrivalEpochSForPick;

manualArrivalPicks.eventFirstArrivalUTC = ...
    eventFirstArrivalUTCForPick;
manualArrivalPicks.eventLastArrivalUTC = ...
    eventLastArrivalUTCForPick;

manualArrivalPicks.timeFromEventFirstArrivalS = ...
    timeFromEventFirstArrivalS;

associatedPicks = manualArrivalPicks( ...
    ~isnan(manualArrivalPicks.eventNumber), ...
    : ...
);

unassociatedPicks = manualArrivalPicks( ...
    isnan(manualArrivalPicks.eventNumber), ...
    : ...
);

representedEvents = unique(associatedPicks.eventNumber);

fprintf('   Total associated picks: %d\n', height(associatedPicks));
fprintf('   Unassociated picks: %d\n', height(unassociatedPicks));
fprintf('   Events represented: %d of %d\n', ...
    numel(representedEvents), ...
    nEvents);
fprintf('   Ambiguous associations left unassigned: %d\n', ...
    sum(manualArrivalPicks.associationAmbiguous));

%% ------------------------------------------------------------------------
% 6. Validate stored 153-event boundaries
% -------------------------------------------------------------------------

fprintf('6. Validating event boundaries...\n');

eventValidationRows = struct( ...
    'eventNumber', {}, ...
    'nAssociatedPicks', {}, ...
    'nAcceptedInfrasoundNPicks', {}, ...
    'firstDifferenceMs', {}, ...
    'lastDifferenceMs', {}, ...
    'passesTolerance', {} ...
);

for eventIndex = 1:nEvents

    eventRows = associatedPicks( ...
        associatedPicks.eventNumber == eventIndex, ...
        : ...
    );

    acceptedNRows = eventRows( ...
        lower(strip(eventRows.phase)) == "n" ...
        & eventRows.isInfrasoundChannel, ...
        : ...
    );

    if isempty(acceptedNRows)

        firstDifferenceMs = NaN;
        lastDifferenceMs = NaN;
        passesTolerance = false;

    else

        firstDifferenceMs = ...
            (min(acceptedNRows.matlabDatenum) ...
            - infrasoundEvent(eventIndex).FirstArrivalTime) ...
            * 86400 * 1000;

        lastDifferenceMs = ...
            (max(acceptedNRows.matlabDatenum) ...
            - infrasoundEvent(eventIndex).LastArrivalTime) ...
            * 86400 * 1000;

        passesTolerance = ...
            abs(firstDifferenceMs) <= ...
                EVENT_BOUNDARY_VALIDATION_TOLERANCE_MS ...
            && ...
            abs(lastDifferenceMs) <= ...
                EVENT_BOUNDARY_VALIDATION_TOLERANCE_MS;
    end

    eventValidationRows(end + 1) = struct( ... %#ok<SAGROW>
        'eventNumber', eventIndex, ...
        'nAssociatedPicks', height(eventRows), ...
        'nAcceptedInfrasoundNPicks', height(acceptedNRows), ...
        'firstDifferenceMs', firstDifferenceMs, ...
        'lastDifferenceMs', lastDifferenceMs, ...
        'passesTolerance', passesTolerance ...
    );
end

eventValidation = struct2table(eventValidationRows);

nValidated = sum(eventValidation.passesTolerance);

fprintf( ...
    '   Events matching stored first/last infrasound N picks: %d of %d\n', ...
    nValidated, ...
    nEvents ...
);

failedEvents = eventValidation( ...
    ~eventValidation.passesTolerance, ...
    : ...
);

missingEvents = setdiff( ...
    (1:nEvents)', ...
    representedEvents ...
);

if ~isempty(failedEvents)
    fprintf('   Events failing validation: %s\n', ...
        mat2str(failedEvents.eventNumber'));
end

if ~isempty(missingEvents)
    fprintf('   Events with no associated picks: %s\n', ...
        mat2str(missingEvents'));
end

%% ------------------------------------------------------------------------
% 7. Create a broad pick subset
% -------------------------------------------------------------------------

fprintf('7. Creating broad pick subset...\n');

inAccidentWindow = ...
    manualArrivalPicks.arrivalTimeUTC >= ACCIDENT_START_UTC ...
    & manualArrivalPicks.arrivalTimeUTC <= ACCIDENT_END_UTC;

accidentArrivalPicks = manualArrivalPicks(inAccidentWindow, :);

fprintf('   Picks in configured interval: %d\n', ...
    height(accidentArrivalPicks));

%% ------------------------------------------------------------------------
% 8. Flatten the legacy 153-event catalogue
% -------------------------------------------------------------------------

fprintf('8. Exporting flat 153-event legacy catalogue...\n');

eventNumber = (1:nEvents)';

firstArrivalDatenum = nan(nEvents, 1);
lastArrivalDatenum = nan(nEvents, 1);

firstArrivalEpochS = nan(nEvents, 1);
lastArrivalEpochS = nan(nEvents, 1);

firstArrivalUTC = NaT(nEvents, 1, 'TimeZone', 'UTC');
lastArrivalUTC = NaT(nEvents, 1, 'TimeZone', 'UTC');

meanCorr = nan(nEvents, 1);
stdCorr = nan(nEvents, 1);
meanSecsDiff = nan(nEvents, 1);
stdSecsDiff = nan(nEvents, 1);

bestBackAzimuthDeg = nan(nEvents, 1);
bestSoundSpeedMps = nan(nEvents, 1);
apparentSpeedMps = nan(nEvents, 1);
apparentSpeedErrorMps = nan(nEvents, 1);

reducedPressure1Pa = nan(nEvents, 1);
reducedPressure2Pa = nan(nEvents, 1);
reducedPressure3Pa = nan(nEvents, 1);

infrasoundEnergyJ = nan(nEvents, 1);
seismicEnergyJ = nan(nEvents, 1);

snr1 = nan(nEvents, 1);
snr2 = nan(nEvents, 1);
snr3 = nan(nEvents, 1);

nAssociatedPicks = zeros(nEvents, 1);
nNPhasePicks = zeros(nEvents, 1);
nInfrasoundChannelPicks = zeros(nEvents, 1);
nSeismicChannelPicks = zeros(nEvents, 1);

for eventIndex = 1:nEvents

    event = infrasoundEvent(eventIndex);

    t0 = event.FirstArrivalTime;
    t1 = event.LastArrivalTime;

    firstArrivalDatenum(eventIndex) = t0;
    lastArrivalDatenum(eventIndex) = t1;

    firstArrivalEpochS(eventIndex) = ...
        (t0 - UNIX_EPOCH_DATENUM) * 86400;

    lastArrivalEpochS(eventIndex) = ...
        (t1 - UNIX_EPOCH_DATENUM) * 86400;

    firstArrivalUTC(eventIndex) = datetime( ...
        t0, ...
        'ConvertFrom', 'datenum', ...
        'TimeZone', 'UTC' ...
    );

    lastArrivalUTC(eventIndex) = datetime( ...
        t1, ...
        'ConvertFrom', 'datenum', ...
        'TimeZone', 'UTC' ...
    );

    meanCorr(eventIndex) = event.meanCorr;
    stdCorr(eventIndex) = event.stdCorr;
    meanSecsDiff(eventIndex) = event.meanSecsDiff;
    stdSecsDiff(eventIndex) = event.stdSecsDiff;

    bestBackAzimuthDeg(eventIndex) = event.bestbackaz;
    bestSoundSpeedMps(eventIndex) = event.bestsoundspeed;
    apparentSpeedMps(eventIndex) = event.apparentSpeed;
    apparentSpeedErrorMps(eventIndex) = event.apparentSpeedError;

    if numel(event.reducedPressure) >= 3
        reducedPressure1Pa(eventIndex) = event.reducedPressure(1);
        reducedPressure2Pa(eventIndex) = event.reducedPressure(2);
        reducedPressure3Pa(eventIndex) = event.reducedPressure(3);
    end

    infrasoundEnergyJ(eventIndex) = event.infrasoundEnergy;
    seismicEnergyJ(eventIndex) = event.seismicEnergy;

    if numel(event.snr) >= 3
        snr1(eventIndex) = event.snr(1);
        snr2(eventIndex) = event.snr(2);
        snr3(eventIndex) = event.snr(3);
    end

    rows = associatedPicks( ...
        associatedPicks.eventNumber == eventIndex, ...
        : ...
    );

    nAssociatedPicks(eventIndex) = height(rows);
    nNPhasePicks(eventIndex) = sum(lower(strip(rows.phase)) == "n");
    nInfrasoundChannelPicks(eventIndex) = ...
        sum(rows.isInfrasoundChannel);
    nSeismicChannelPicks(eventIndex) = ...
        sum(rows.isSeismicChannel);
end

firstArrivalUTC.Format = DATETIME_FORMAT;
lastArrivalUTC.Format = DATETIME_FORMAT;

legacyEventCatalogue = table( ...
    eventNumber, ...
    firstArrivalDatenum, ...
    lastArrivalDatenum, ...
    firstArrivalEpochS, ...
    lastArrivalEpochS, ...
    firstArrivalUTC, ...
    lastArrivalUTC, ...
    meanCorr, ...
    stdCorr, ...
    meanSecsDiff, ...
    stdSecsDiff, ...
    bestBackAzimuthDeg, ...
    bestSoundSpeedMps, ...
    apparentSpeedMps, ...
    apparentSpeedErrorMps, ...
    reducedPressure1Pa, ...
    reducedPressure2Pa, ...
    reducedPressure3Pa, ...
    infrasoundEnergyJ, ...
    seismicEnergyJ, ...
    snr1, ...
    snr2, ...
    snr3, ...
    nAssociatedPicks, ...
    nNPhasePicks, ...
    nInfrasoundChannelPicks, ...
    nSeismicChannelPicks ...
);

%% ------------------------------------------------------------------------
% 9. Optionally export catalog.mat as the 157-event catalogue
% -------------------------------------------------------------------------

fprintf('9. Checking for 157-event catalog.mat...\n');

catalog157 = table();
catalogobj = [];

if isfile(CATALOG_MAT_FILE)

    catalogData = load(CATALOG_MAT_FILE);

    if isfield(catalogData, 'catalogobj')

        catalogobj = catalogData.catalogobj;

        onTimeDatenum = catalogobj.ontime(:);
        offTimeDatenum = catalogobj.offtime(:);

        if numel(onTimeDatenum) ~= numel(offTimeDatenum)
            error( ...
                ['catalogobj.ontime and catalogobj.offtime have ' ...
                 'different lengths.'] ...
            );
        end

        nCatalogEvents = numel(onTimeDatenum);
        catalogEventNumber = (1:nCatalogEvents)';

        onTimeEpochS = ...
            (onTimeDatenum - UNIX_EPOCH_DATENUM) * 86400;

        offTimeEpochS = ...
            (offTimeDatenum - UNIX_EPOCH_DATENUM) * 86400;

        onTimeUTC = datetime( ...
            onTimeDatenum, ...
            'ConvertFrom', 'datenum', ...
            'TimeZone', 'UTC' ...
        );

        offTimeUTC = datetime( ...
            offTimeDatenum, ...
            'ConvertFrom', 'datenum', ...
            'TimeZone', 'UTC' ...
        );

        onTimeUTC.Format = DATETIME_FORMAT;
        offTimeUTC.Format = DATETIME_FORMAT;

        durationS = ...
            (offTimeDatenum - onTimeDatenum) * 86400;

        catalog157 = table( ...
            catalogEventNumber, ...
            onTimeDatenum, ...
            offTimeDatenum, ...
            onTimeEpochS, ...
            offTimeEpochS, ...
            onTimeUTC, ...
            offTimeUTC, ...
            durationS ...
        );

        writetable( ...
            catalog157, ...
            fullfile( ...
                OUTPUT_DIR, ...
                'legacy_catalog_157_events.csv' ...
            ) ...
        );

        save( ...
            fullfile( ...
                OUTPUT_DIR, ...
                'legacy_catalog_157_events.mat' ...
            ), ...
            'catalog157', ...
            'catalogobj', ...
            '-v7.3' ...
        );

        fprintf( ...
            '   Exported %d catalogue events from catalog.mat.\n', ...
            height(catalog157) ...
        );

    else
        warning('catalog.mat does not contain catalogobj.');
    end

else
    fprintf('   catalog.mat not found; skipping 157-event export.\n');
end

%% ------------------------------------------------------------------------
% 10. Write durable exports
% -------------------------------------------------------------------------

fprintf('10. Writing exports...\n');

writetable( ...
    manualArrivalPicks, ...
    fullfile(OUTPUT_DIR, 'manual_arrival_picks.csv') ...
);

writetable( ...
    accidentArrivalPicks, ...
    fullfile(OUTPUT_DIR, 'accident_arrival_picks.csv') ...
);

writetable( ...
    associatedPicks, ...
    fullfile(OUTPUT_DIR, 'explosion_event_arrival_picks.csv') ...
);

writetable( ...
    unassociatedPicks, ...
    fullfile(OUTPUT_DIR, 'unassociated_arrival_picks.csv') ...
);

writetable( ...
    legacyEventCatalogue, ...
    fullfile(OUTPUT_DIR, 'legacy_infrasound_event_catalogue.csv') ...
);

writetable( ...
    eventValidation, ...
    fullfile(OUTPUT_DIR, 'event_pick_association_validation.csv') ...
);

saveVariables = { ...
    'manualArrivalPicks', ...
    'accidentArrivalPicks', ...
    'associatedPicks', ...
    'unassociatedPicks', ...
    'legacyEventCatalogue', ...
    'eventValidation', ...
    'arrivals', ...
    'infrasoundEvent', ...
    'wevent' ...
};

if ~isempty(catalog157)
    saveVariables{end + 1} = 'catalog157';
    saveVariables{end + 1} = 'catalogobj';
end

save( ...
    fullfile(OUTPUT_DIR, 'legacy_spacex_archive.mat'), ...
    saveVariables{:}, ...
    '-v7.3' ...
);

%% ------------------------------------------------------------------------
% 11. Write a human-readable summary
% -------------------------------------------------------------------------

fprintf('11. Writing summary report...\n');

summaryFile = fullfile(OUTPUT_DIR, 'legacy_export_summary.txt');
fid = fopen(summaryFile, 'w');

if fid < 0
    error('Could not create %s', summaryFile);
end

cleanupSummary = onCleanup(@() fclose(fid));

fprintf(fid, 'Legacy Falcon 9 MATLAB/GISMO export summary\n');
fprintf(fid, '==========================================\n\n');

fprintf(fid, 'Input MAT file:\n  %s\n\n', INPUT_MAT_FILE);

fprintf(fid, 'Time representation\n');
fprintf(fid, '-------------------\n');
fprintf(fid, [ ...
    'All important times are exported as MATLAB datenum, Unix epoch ' ...
    'seconds, and UTC datetime formatted to milliseconds. Epoch seconds ' ...
    'are recommended for Python interchange.\n\n' ...
]);

fprintf(fid, 'Manual picks\n');
fprintf(fid, '------------\n');
fprintf(fid, 'Total picks: %d\n', height(manualArrivalPicks));
fprintf(fid, 'Parsed channel identifiers: %d\n', ...
    sum(manualArrivalPicks.channelParseSucceeded));
fprintf(fid, 'Deleted-phase picks: %d\n', ...
    sum(manualArrivalPicks.isDeleted));
fprintf(fid, 'N-phase picks: %d\n', ...
    sum(manualArrivalPicks.isInfrasoundPhase));
fprintf(fid, 'Seismic P/S phase picks: %d\n', ...
    sum(manualArrivalPicks.isSeismicPhase));
fprintf(fid, 'Unclassified-phase picks: %d\n\n', ...
    sum(manualArrivalPicks.isUnclassifiedPhase));

fprintf(fid, 'Picks by channel\n');
fprintf(fid, '----------------\n');

channelCounts = groupsummary( ...
    manualArrivalPicks, ...
    {'station', 'location', 'channel'} ...
);

for rowIndex = 1:height(channelCounts)
    fprintf( ...
        fid, ...
        '%s.%s.%s: %d\n', ...
        channelCounts.station(rowIndex), ...
        channelCounts.location(rowIndex), ...
        channelCounts.channel(rowIndex), ...
        channelCounts.GroupCount(rowIndex) ...
    );
end

fprintf(fid, '\n153-event associations\n');
fprintf(fid, '----------------------\n');
fprintf(fid, 'Legacy events: %d\n', nEvents);
fprintf(fid, 'Associated picks: %d\n', height(associatedPicks));
fprintf(fid, 'Unassociated picks: %d\n', height(unassociatedPicks));
fprintf(fid, 'Events represented: %d\n', numel(representedEvents));
fprintf(fid, 'Ambiguous pick associations: %d\n', ...
    sum(manualArrivalPicks.associationAmbiguous));
fprintf(fid, 'Events passing first/last N-pick validation: %d\n\n', ...
    nValidated);

if ~isempty(catalog157)
    fprintf(fid, '157-event catalog.mat export\n');
    fprintf(fid, '----------------------------\n');
    fprintf(fid, 'Catalogue events: %d\n\n', height(catalog157));
end

fprintf(fid, 'Configured pick interval\n');
fprintf(fid, '------------------------\n');
fprintf(fid, 'Start: %s\n', string(ACCIDENT_START_UTC));
fprintf(fid, 'End:   %s\n', string(ACCIDENT_END_UTC));
fprintf(fid, 'Picks in interval: %d\n\n', ...
    height(accidentArrivalPicks));

fprintf(fid, 'Important interpretation\n');
fprintf(fid, '------------------------\n');
fprintf(fid, [ ...
    'The manual pick table is the primary archival product. Legacy ' ...
    'amplitudes, energies, reduced pressures, and array results are ' ...
    'retained for comparison, but should be recomputed from the modern ' ...
    'response-corrected waveform stream where possible.\n' ...
]);

clear cleanupSummary;

%% ------------------------------------------------------------------------
% 12. Print completion summary
% -------------------------------------------------------------------------

fprintf('\nCompleted legacy export.\n\n');
fprintf('Primary outputs:\n');
fprintf('  %s\n', fullfile(OUTPUT_DIR, 'manual_arrival_picks.csv'));
fprintf('  %s\n', fullfile(OUTPUT_DIR, 'accident_arrival_picks.csv'));
fprintf('  %s\n', fullfile(OUTPUT_DIR, 'explosion_event_arrival_picks.csv'));
fprintf('  %s\n', fullfile(OUTPUT_DIR, 'legacy_infrasound_event_catalogue.csv'));

if ~isempty(catalog157)
    fprintf('  %s\n', ...
        fullfile(OUTPUT_DIR, 'legacy_catalog_157_events.csv'));
end

fprintf('  %s\n', fullfile(OUTPUT_DIR, 'legacy_spacex_archive.mat'));
fprintf('  %s\n', fullfile(OUTPUT_DIR, 'legacy_export_summary.txt'));

fprintf('\nRecommended next step:\n');
fprintf([ ...
    '  Load the epoch-second columns in Python. Compare the 153-event ' ...
    'infrasoundEvent catalogue, the 157-event catalog.mat catalogue, and ' ...
    'events reconstructed directly from the preserved manual picks.\n' ...
]);
