service_run:
  id: 20260922_service
  start_date: '2026-09-22'
  end_date: '2026-09-24'
paths:
  raw: 00_download
  conversion: 10_conversion
  ingest: 20_ingest
  qc: 30_qc
sources:
  centaur:
    enabled: true
    input: 00_download/Centaur
    mode: fast
  gem:
    enabled: true
    raw: 00_download/Gem/raw
    converted: 10_conversion/Gem/mseed
  silicon_audio:
    enabled: true
    input: 00_download/SiliconAudio
  guralp:
    enabled: true
    input: 00_download/Guralp
  smartsolo:
    enabled: true
    input: 00_download/SmartSolo
  pegasus:
    enabled: false
    input: 00_download/Pegasus
